---
- name: Add the apt repository.
  apt_repository:
    repo: 'deb http://apt.newrelic.com/debian/ newrelic non-free'
    state: present

- name: Add the apt key.
  apt_key:
    url: https://download.newrelic.com/548C16BF.gpg
    state: present
  sudo: yes

- name: Install newrelic packages.
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: newrelic_packages
