---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: install-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Define newrelic_ini_path.
  set_fact:
    newrelic_ini_path: "{{ __newrelic_ini_path }}"
  when: newrelic_ini_path is not defined

- name: Define php_webserver_daemon.
  set_fact:
    php_webserver_daemon: "{{ __php_webserver_daemon }}"
  when: php_webserver_daemon is not defined

- name: Copy newrelic.ini.
  template:
    src: newrelic.ini.j2
    dest: "{{ newrelic_ini_path }}"
  notify: restart webserver

- name: Enable newrelic to start on boot.
  service:
    name: "{{ newrelic_daemon }}"
    state: started
    enabled: yes
